### PR TITLE
Integrate with 6.5

### PR DESCRIPTION
**Pull request by BaldBeacon**
This commit merges the code in the master branch with the cfe 6.6 to make both compatible.

### CODE REVIEW

**Comment by SpaceSteve121** [comment]
@BaldBeacon Will review once checks are passing. Looks like unit tests haven't been updated yet.

**Comment by SpaceSteve121** [comment]
I think we might want to run the unit tests under CFE 6.6 as well as 6.5. What do you think? Handle here or in separate PR?

Also, can you clarify your plan? master has the 6.5 version of ECI but these changes are coming from an integrate-with-6.5 branch... are you planning to open a PR for the cfe-6.6 branch into master after this?

**Comment by BaldBeacon** [comment]
> I think we might want to run the unit tests under CFE 6.6 as well as 6.5. What do you think? Handle here or in separate PR?
> 
> Also, can you clarify your plan? master has the 6.5 version of ECI but these changes are coming from an integrate-with-6.5 branch... are you planning to open a PR for the cfe-6.6 branch into master after this?

I'm still looking for a standard way to write unit tests with UT assert matching what's expected with the cFE 6.6 cmake system. I was hoping those could be written at a future time when I know more about how UT was expected to work with non-cfe core apps.

The plan was to use this branch as an integration step between cFE 6.5 and cFE 6.6. Since we determined ECI should support both I thought it was fitting to include this into the cFE 6.6 branch to eventually be merged into master.

**Comment by SpaceSteve121** [comment]
Perhaps open an issue on the CFE/CFS repo requesting some documentation on the changes to the UT framework and/or an example implementation of some unit tests in one of the apps they include?

Also, perhaps open an issue here documenting the need to run the unit tests under 6.6 (and link to the CFE/CFS UT issue) to be handled later? and then we'll merge this PR?

> as an integration step between cFE 6.5 and cFE 6.6

What other steps need to be completed before we could merge 6.6 into master?

**Comment by BaldBeacon** [comment]
> Perhaps open an issue on the CFE/CFS repo requesting some documentation on the changes to the UT framework and/or an example implementation of some unit tests in one of the apps they include?
> 
> Also, perhaps open an issue here documenting the need to run the unit tests under 6.6 (and link to the CFE/CFS UT issue) to be handled later? and then we'll merge this PR?

I've opened an issue #25 to address the documentation of the ECI and an issue in the cFS repo nasa/cFS#4 to gather more information on how to approach #25. This issue will most likely not be answered until we get more information on how to do the UT testing in 6.6.

> 
> > as an integration step between cFE 6.5 and cFE 6.6
>
> What other steps need to be completed before we could merge 6.6 into master

ECI should be functionally ready for both cFE 6.5 and 6.6 following this MR. Next we should expect a separate MR to merge the cfe-6.6 branch into master.

**Review by SpaceSteve121 — APPROVED** [review]

**Pull request merged**
