### PR TITLE
Update ECI to be compatible with cFE 6.6

### PR DESCRIPTION
**Pull request by BaldBeacon**
ECI has been 6.6 compatible for a while now but we've decided to allow ECI to work with 6.5 (using the make system) and 6.6 (using cmake) rather than make a separate 6.5 release. Since the NASA PACE project uses cFE 6.5 and ECI it makes sense that they should still be able to benefit from newer features in ECI.

Changes:
* Added basic Doxygen documentation to ECI source code
* Added files needed for cmake build system to example apps to support CFE 6.6
* Updated CI pipeline to build example apps under both CFE 6.5 and 6.6
* Updated MID's in example apps to resolve collision with CFS default apps
* Fixed MID's in example apps so that they're consistent with the cmd/tlm header in packet

### CODE REVIEW

**Comment by SpaceSteve121** [comment]
@BaldBeacon Do you mind putting together a commit message for this, summarizing all the changes? Its a rather long list and I'm not sure I'll have time today.

**Comment by BaldBeacon** [comment]
Will do, I'll place it into the merge request's description.

**Comment by SpaceSteve121** [comment]
@BaldBeacon I went through and attempted to summarize the changes in this PR in the PR description, but I think we still have some loose ends:

* It looks like a bunch of rst files were committed. Are those autogenerated from the code? If so, was committing them intentional? What ensures they stay up to date? 
* It looks like (some parts?) of doxyrest might be included now in the ECI repo now? That's not reflected in the commit notes.

**Comment by BaldBeacon** [comment]
> * It looks like a bunch of rst files were committed. Are those autogenerated from the code? If so, was committing them intentional? What ensures they stay up to date?
> * It looks like (some parts?) of doxyrest might be included now in the ECI repo now? That's not reflected in the commit notes.

Good catch, I just noticed those on my branch as well but I didn't know they came from here. Not really sure how those got into this branch but I'll get rid of them.

**Pull request merged**
